#!/usr/bin/env node
// Clawdius forbidden-content scan. Flags Copilot/GitHub-Copilot branding, known Microsoft
// telemetry keys, and Amazon-internal terms (from an env-referenced wordlist that is never
// committed) in CLAWDIUS-AUTHORED content only. The upstream VS Code tree legitimately contains
// "copilot" until that chrome is removed, so this scan deliberately skips upstream paths.
// It inspects Clawdius-owned files in full, and for upstream files carrying a CLAWDIUS-BEGIN
// marker it inspects ONLY the marked Clawdius regions (so an in-place edit to a Copilot-laden
// upstream file like defaultAccount.ts does not trip on the surrounding upstream code).
//
// Usage: node script/clawdius/scan-forbidden.ts [--largefiles] <files...>
// Exit 1 on any finding.
import fs from 'node:fs'

const args = process.argv.slice(2)
const largeFilesMode = args.includes('--largefiles')
const files = args.filter((a) => !a.startsWith('--'))

// Clawdius-owned path prefixes the content scan applies to (scanned in full).
const OWNED = [/^clawdius\//, /^src\/vs\/workbench\/contrib\/clawdius\//, /^src\/vs\/platform\/clawdius\//,
  /^script\/clawdius\//, /^test\/clawdius\//, /^extensions\/clawdius-/, /^CHANGES_AGAINST_UPSTREAM\.md$/,
  /^MERGING\.md$/, /^BUILD\.md$/, /^README-CLAWDIUS/]
const MARKER_BEGIN = 'CLAWDIUS-BEGIN'
const MARKER_END = 'CLAWDIUS-END'

// The scanner's own source legitimately contains every forbidden pattern (the rule literals).
// Never scan it, or the gate flags itself.
const SELF = /(^|\/)script\/clawdius\/scan-forbidden\.ts$/
// Files that must be able to NAME what Clawdius removes (Copilot / GitHub Copilot): the policy +
// ledger docs, and branding-guard.ts (which asserts the brand is ABSENT, so it embeds the term). They
// stay subject to telemetry-key and Amazon-internal checks; only brand mentions are allowed. SELF
// already excludes the scanner itself, so this is a by-name list, not a directory-wide exemption.
const BRAND_EXEMPT = [/^clawdius\/SECURITY-SCANNING\.md$/, /^clawdius\/PRIVACY\.md$/, /^CHANGES_AGAINST_UPSTREAM\.md$/,
  /^MERGING\.md$/, /^BUILD\.md$/, /^README-CLAWDIUS/, /(^|\/)script\/clawdius\/branding-guard\.ts$/,
  /(^|\/)script\/clawdius\/brand-ratchet\.ts$/, /(^|\/)script\/clawdius\/brand-ratchet-baseline\.json$/]
const BRANDING_IDS = new Set(['copilot-brand', 'github-copilot-brand'])

const FORBIDDEN = [
  { id: 'copilot-brand', re: /\bcopilot\b/i },
  { id: 'github-copilot-brand', re: /github\s+copilot/i },
  { id: 'ms-instrumentation-key', re: /InstrumentationKey=/i },
  { id: 'ms-aiconfig', re: /aiKey"?\s*[:=]/i },
]

// UNIVERSAL rules run on EVERY scanned file regardless of OWNED/marked scoping: these markers of an internal
// drafting workflow have no legitimate use anywhere in the public tree. They are what a bare
// Clawdius-authored doc (no CLAWDIUS-BEGIN marker) would otherwise slip past. Kept deliberately narrow to the
// unambiguous process terms so ordinary "phase"/"wave" code comments never trip.
const UNIVERSAL = [
  { id: 'internal-process', re: /\bsuper-planner\b|\bgrill-with-docs\b|\bgrill-me\b|council synthesis|[0-9][\s-]?model council|Generated by super-planner/i },
]
// Internal planning documents must not appear in the public source tree.
const INTERNAL_DOC_PATH = /^src\/.*(-plan\.md|\/roadmap[^/]*\.md)$/i
// The CI workflow legitimately carries the UNIVERSAL marker literals (it is the guard that greps for them),
// so exempt it from the universal content rule - the same reason SELF exempts the scanner's own source.
const UNIVERSAL_EXEMPT = [/(^|\/)\.github\/workflows\/clawdius-ci\.yml$/]

// Amazon-internal wordlist (path supplied via env, never committed).
let internal: string[] = []
const wlPath = process.env.CLAWDIUS_INTERNAL_WORDLIST
if (wlPath && fs.existsSync(wlPath)) {
  internal = fs.readFileSync(wlPath, 'utf8').split(/\r?\n/).map((s) => s.trim()).filter(Boolean)
}

// Pull only the text inside CLAWDIUS-BEGIN..CLAWDIUS-END spans (inclusive). An unterminated span
// runs to EOF (over-scan is safe). Used for marked in-place edits to upstream files.
function markedRegions(text: string): string {
  const out: string[] = []
  let inRegion = false
  for (const line of text.split(/\r?\n/)) {
    if (line.includes(MARKER_BEGIN)) { inRegion = true; out.push(line); continue }
    if (line.includes(MARKER_END)) { out.push(line); inRegion = false; continue }
    if (inRegion) { out.push(line) }
  }
  return out.join('\n')
}

const LARGE_LIMIT = 5 * 1024 * 1024
const LARGE_ALLOW = [/^clawdius\/branding\//, /\.(icns|ico)$/]

let findings = 0
for (const f of files) {
  const nf = f.replace(/\\/g, '/')
  if (largeFilesMode) {
    try {
      const sz = fs.statSync(f).size
      if (sz > LARGE_LIMIT && !LARGE_ALLOW.some((re) => re.test(nf))) {
        console.error(`[large-file] ${f} is ${(sz / 1048576).toFixed(1)} MB (> 5 MB)`) ; findings++
      }
    } catch {}
    continue
  }
  if (SELF.test(nf)) { continue }
  const owned = OWNED.some((re) => re.test(nf))
  let text = ''
  try { text = fs.readFileSync(f, 'utf8') } catch { continue }
  // UNIVERSAL checks apply to every file, not just OWNED/marked ones.
  if (INTERNAL_DOC_PATH.test(nf)) { console.error(`[internal-planning-doc] ${f}: planning docs must not appear in the public source tree`); findings++ }
  if (!UNIVERSAL_EXEMPT.some((re) => re.test(nf))) {
    for (const rule of UNIVERSAL) {
      if (rule.re.test(text)) { console.error(`[${rule.id}] forbidden content in ${f}`); findings++ }
    }
  }
  const marked = !owned && text.includes(MARKER_BEGIN)
  if (!owned && !marked) { continue }
  // Owned files: scan the whole file. Marked upstream edits: scan only the Clawdius regions, and treat
  // them as brand-exempt (the comments legitimately describe the Copilot they neutralize) while still
  // checking telemetry keys + internal terms.
  const scanText = owned ? text : markedRegions(text)
  const brandExempt = marked || BRAND_EXEMPT.some((re) => re.test(nf))
  for (const rule of FORBIDDEN) {
    if (brandExempt && BRANDING_IDS.has(rule.id)) { continue }
    if (rule.re.test(scanText)) { console.error(`[${rule.id}] forbidden content in ${f}`); findings++ }
  }
  for (const term of internal) {
    if (term && scanText.toLowerCase().includes(term.toLowerCase())) {
      console.error(`[amazon-internal] term match in ${f}`); findings++
    }
  }
}

if (findings) { console.error(`\nForbidden-content scan failed: ${findings} finding(s).`); process.exit(1) }
process.exit(0)
